USE [C:\USERS\DANIEL\DOWNLOADS\FI.WEBATIVIDADEENTREVISTA\FI.WEBATIVIDADEENTREVISTA\APP_DATA\BANCODEDADOS.MDF]
GO

CREATE OR ALTER PROC dbo.FI_SP_AltBenef
	@CPF           CHAR (11),
    @NOME          VARCHAR (50),
	@ID			   BIGINT
AS
BEGIN
	UPDATE dbo.BENEFICIARIOS 
	SET 
		CPF = @CPF,
		NOME = @NOME
	WHERE ID = @ID
END