USE [C:\USERS\DANIEL\DOWNLOADS\FI.WEBATIVIDADEENTREVISTA\FI.WEBATIVIDADEENTREVISTA\APP_DATA\BANCODEDADOS.MDF]
GO

CREATE OR ALTER PROC dbo.FI_SP_IncBenef
    @CPF           CHAR (11),
    @NOME          VARCHAR (50) ,
	@IDCLIENTE     BIGINT
AS
BEGIN
	INSERT INTO dbo.BENEFICIARIOS (CPF, NOME, IDCLIENTE)
	VALUES (@CPF, @NOME, @IDCLIENTE)

	SELECT SCOPE_IDENTITY()
END