USE [C:\USERS\DANIEL\DOWNLOADS\FI.WEBATIVIDADEENTREVISTA\FI.WEBATIVIDADEENTREVISTA\APP_DATA\BANCODEDADOS.MDF]
GO

CREATE OR ALTER PROC dbo.FI_SP_DelBenef
	@ID BIGINT
AS
BEGIN
	DELETE dbo.BENEFICIARIOS WHERE ID = @ID
END