USE [C:\USERS\DANIEL\DOWNLOADS\FI.WEBATIVIDADEENTREVISTA\FI.WEBATIVIDADEENTREVISTA\APP_DATA\BANCODEDADOS.MDF]
GO

CREATE OR ALTER PROC dbo.FI_SP_VerificaBenef
	@CPF CHAR(11),
	@IDCLIENTE BIGINT,
	@ID BIGINT=NULL
AS
BEGIN
	IF(@ID IS NULL)
		SELECT 1 FROM dbo.BENEFICIARIOS WHERE CPF = @CPF AND IDCLIENTE = @IDCLIENTE
	ELSE
		SELECT 1 FROM dbo.BENEFICIARIOS WHERE CPF = @CPF AND IDCLIENTE = @IDCLIENTE AND ID <> @ID
END