USE [C:\USERS\DANIEL\DOWNLOADS\FI.WEBATIVIDADEENTREVISTA\FI.WEBATIVIDADEENTREVISTA\APP_DATA\BANCODEDADOS.MDF]
GO

ALTER TABLE dbo.BENEFICIARIOS
ALTER COLUMN CPF CHAR(11) NOT NULL

CREATE UNIQUE NONCLUSTERED INDEX IX_BENEFICIARIOS_IDCLIENTE_CPF ON dbo.BENEFICIARIOS (IDCLIENTE ASC, CPF ASC)
GO