USE [C:\USERS\DANIEL\DOWNLOADS\FI.WEBATIVIDADEENTREVISTA\FI.WEBATIVIDADEENTREVISTA\APP_DATA\BANCODEDADOS.MDF]
GO

CREATE OR ALTER PROC dbo.FI_SP_VerificaCliente
	@CPF CHAR(11),
	@ID BIGINT=NULL
AS
BEGIN
	IF(@ID IS NULL)
		SELECT 1 FROM dbo.CLIENTES WHERE CPF = @CPF
	ELSE
		SELECT 1 FROM dbo.CLIENTES WHERE CPF = @CPF AND ID <> @ID
END