USE [C:\USERS\DANIEL\DOWNLOADS\FI.WEBATIVIDADEENTREVISTA\FI.WEBATIVIDADEENTREVISTA\APP_DATA\BANCODEDADOS.MDF]
GO

CREATE OR ALTER PROC dbo.FI_SP_ContarBenefCliente
	@ID BIGINT
AS
	BEGIN
		SELECT COUNT(*) FROM dbo.BENEFICIARIOS WHERE IDCLIENTE=@ID
	END